sonar.projectKey=anpd-sei-integrations
sonar.projectName=ANPD SEI Integrations


sonar.sources=packages
sonar.tests=packages

sonar.sourceEncoding=UTF-8

sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/coverage/**,\
**/types/**,\
**/*.d.ts,\
**/*.config.*,\
**/vitest.config.*,\
**/tsup.config.*

sonar.test.inclusions=\
**/*.test.ts,\
**/*.test.tsx,\
**/*.spec.ts,\
**/*.spec.tsx

sonar.coverage.exclusions=\
**/*.test.ts,\
**/*.test.tsx,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.d.ts,\
**/index.ts,\
**/*.config.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info
