export { createSipClient, SipClient, SipConsultasClient, SipReplicacaoClient } from "./client"
export {
  callSipSoap,
  createSoapArray,
  buildSipSoapEnvelope,
  parseSipSoapResponse,
  SipSoapError,
} from "./soap"
export type {
  SipBuscarUsuariosParams,
  SipBuscarUsuariosSemPermissaoParams,
  SipCarregarUsuarioParams,
  SipConfig,
  SipFiltroRecursosMenus,
  SipListarOrgaosParams,
  SipListarPerfisParams,
  SipListarPermissoesParams,
  SipListarRecursosParams,
  SipListarUnidadesParams,
  SipOperacaoReplicacao,
  SipOrgao,
  SipPerfil,
  SipPermissao,
  SipPesquisarUsuarioParams,
  SipRawMap,
  SipRawValue,
  SipReplicarPermissao,
  SipReplicarUsuario,
  SipScalarSoapValue,
  SipSoapArrayValue,
  SipSoapCallOptions,
  SipSoapParamValue,
  SipSoapStructValue,
  SipUnidade,
  SipUsuario,
  SipUsuarioComPermissoes,
  SipUsuarioDiretorio,
} from "./types"

export {
  createSipClient as createSeiSipClient,
  SipClient as SeiSipClient,
  SipConsultasClient as SeiSipConsultasClient,
  SipReplicacaoClient as SeiSipReplicacaoClient,
} from "./client"
export {
  buildSipSoapEnvelope as buildSeiSipSoapEnvelope,
  callSipSoap as callSeiSipSoap,
  parseSipSoapResponse as parseSeiSipSoapResponse,
  SipSoapError as SeiSipSoapError,
} from "./soap"
export type {
  SipBuscarUsuariosParams as SeiSipBuscarUsuariosParams,
  SipBuscarUsuariosSemPermissaoParams as SeiSipBuscarUsuariosSemPermissaoParams,
  SipCarregarUsuarioParams as SeiSipCarregarUsuarioParams,
  SipConfig as SeiSipConfig,
  SipFiltroRecursosMenus as SeiSipFiltroRecursosMenus,
  SipListarOrgaosParams as SeiSipListarOrgaosParams,
  SipListarPerfisParams as SeiSipListarPerfisParams,
  SipListarPermissoesParams as SeiSipListarPermissoesParams,
  SipListarRecursosParams as SeiSipListarRecursosParams,
  SipListarUnidadesParams as SeiSipListarUnidadesParams,
  SipOperacaoReplicacao as SeiSipOperacaoReplicacao,
  SipOrgao as SeiSipOrgao,
  SipPerfil as SeiSipPerfil,
  SipPermissao as SeiSipPermissao,
  SipPesquisarUsuarioParams as SeiSipPesquisarUsuarioParams,
  SipRawMap as SeiSipRawMap,
  SipRawValue as SeiSipRawValue,
  SipReplicarPermissao as SeiSipReplicarPermissao,
  SipReplicarUsuario as SeiSipReplicarUsuario,
  SipScalarSoapValue as SeiSipScalarSoapValue,
  SipSoapArrayValue as SeiSipSoapArrayValue,
  SipSoapCallOptions as SeiSipSoapCallOptions,
  SipSoapParamValue as SeiSipSoapParamValue,
  SipSoapStructValue as SeiSipSoapStructValue,
  SipUnidade as SeiSipUnidade,
  SipUsuario as SeiSipUsuario,
  SipUsuarioComPermissoes as SeiSipUsuarioComPermissoes,
  SipUsuarioDiretorio as SeiSipUsuarioDiretorio,
} from "./types"
