export { createSipClient, SipClient, SipConsultasClient, SipReplicacaoClient } from "./client"
export {
  callSipSoap,
  createSoapArray,
  buildSipSoapEnvelope,
  parseSipSoapResponse,
  SipSoapError,
} from "./soap"
export type {
  SipBuscarUsuariosParams,
  SipBuscarUsuariosSemPermissaoParams,
  SipCarregarUsuarioParams,
  SipConfig,
  SipFiltroRecursosMenus,
  SipGrupoPerfil,
  SipItemMenu,
  SipListarOrgaosParams,
  SipListarPerfisParams,
  SipListarPermissoesParams,
  SipListarRecursosParams,
  SipListarUnidadesParams,
  SipMenu,
  SipOperacaoReplicacaoPermissao,
  SipOperacaoReplicacaoUsuario,
  SipOrgao,
  SipPerfil,
  SipPermissao,
  SipPesquisarUsuarioParams,
  SipRawMap,
  SipRawValue,
  SipRecurso,
  SipReplicarPermissao,
  SipReplicarUsuario,
  SipScalarSoapValue,
  SipSoapArrayValue,
  SipSoapCallOptions,
  SipSoapParamValue,
  SipSoapStructValue,
  SipUnidade,
  SipUsuario,
  SipUsuarioComPermissoes,
  SipUsuarioDiretorio,
} from "./types"
