/**
 * @packageDocumentation
 *
 * Cliente TypeScript para integração SOAP com o SEI.
 *
 * ## Início rápido
 *
 * ```ts
 * import { createSeiClient } from "@anpdgovbr/sei-client"
 *
 * const sei = createSeiClient({
 *   endpointUrl: process.env.SEI_SOAP_ENDPOINT!,
 *   siglaSistema: process.env.SEI_SIGLA_SISTEMA!,
 *   identificacaoServico: process.env.SEI_IDENTIFICACAO_SERVICO!,
 *   requestTimeoutMs: 30_000,
 * })
 *
 * const unidades = await sei.listarUnidades({ idUnidade: "110000001" })
 * const proc = await sei.consultarProcedimento({
 *   idUnidade: "110000001",
 *   protocoloProcedimento: "00000.000001/2026-01",
 * })
 * ```
 *
 * @module
 */
export { SeiClient, SeiConsultasClient, SeiOperacoesClient, createSeiClient } from "./client"
export { encodeSeiBase64 } from "./encoding"
export {
  SeiSoapError,
  buildSeiSoapEnvelope,
  callSeiSoap,
  createSeiSoapArray,
  parseSeiSoapResponse,
} from "./soap"
export type {
  SeiAdicionarArquivoParams,
  SeiAdicionarConteudoArquivoParams,
  SeiAgendarPublicacaoParams,
  SeiAlterarBlocoParams,
  SeiAlterarPublicacaoParams,
  SeiAndamento,
  SeiAndamentoMarcador,
  SeiAnexarProcessoParams,
  SeiAnexo,
  SeiAnexoInput,
  SeiAnotacaoInput,
  SeiArquivoExtensao,
  SeiAssinatura,
  SeiAssunto,
  SeiAssuntoInput,
  SeiAtribuirProcessoParams,
  SeiAtributoAndamento,
  SeiAtributoAndamentoInput,
  SeiAtributoOuvidoria,
  SeiAtributoOuvidoriaInput,
  SeiAtualizarContatosParams,
  SeiBloco,
  SeiBloquearDocumentoParams,
  SeiCampo,
  SeiCampoInput,
  SeiCancelarAgendamentoPublicacaoParams,
  SeiCancelarDocumentoParams,
  SeiCargo,
  SeiCidade,
  SeiConfig,
  SeiConfirmarDisponibilizacaoPublicacaoParams,
  SeiConsultarBlocoParams,
  SeiConsultarDocumentoParams,
  SeiConsultarProcedimentoIndividualParams,
  SeiConsultarProcedimentoParams,
  SeiConsultarPublicacaoParams,
  SeiContato,
  SeiContatoInput,
  SeiControlePrazoProcessosParams,
  SeiDefinicaoControlePrazoInput,
  SeiDefinicaoMarcadorInput,
  SeiDefinirControlePrazoParams,
  SeiDefinirMarcadorParams,
  SeiDesanexarProcessoParams,
  SeiDestinatario,
  SeiDocumentoInput,
  SeiEnviarEmailParams,
  SeiEnviarProcessoParams,
  SeiEstado,
  SeiExcluirBlocoParams,
  SeiExcluirDocumentoParams,
  SeiExcluirProcessoParams,
  SeiFeriado,
  SeiGerarBlocoParams,
  SeiGerarProcedimentoParams,
  SeiHipoteseLegal,
  SeiIncluirDocumentoBlocoParams,
  SeiIncluirDocumentoParams,
  SeiIncluirProcessoBlocoParams,
  SeiInteressado,
  SeiInteressadoInput,
  SeiLancarAndamentoParams,
  SeiListarAndamentosMarcadoresParams,
  SeiListarAndamentosParams,
  SeiListarCargosParams,
  SeiListarCidadesParams,
  SeiListarContatosParams,
  SeiListarEstadosParams,
  SeiListarExtensoesPermitidasParams,
  SeiListarFeriadosParams,
  SeiListarHipotesesLegaisParams,
  SeiListarMarcadoresUnidadeParams,
  SeiListarPaisesParams,
  SeiListarSeriesParams,
  SeiListarTiposConferenciaParams,
  SeiListarTiposPrioridadeParams,
  SeiListarTiposProcedimentoParams,
  SeiListarUnidadesParams,
  SeiListarUsuariosParams,
  SeiMarcador,
  SeiObservacao,
  SeiOperacaoBlocoParams,
  SeiOperacaoProcessoParams,
  SeiPais,
  SeiProcedimentoInput,
  SeiProcedimentoResumido,
  SeiProtocoloBloco,
  SeiPublicacao,
  SeiPublicacaoImprensaNacional,
  SeiPublicacaoImprensaNacionalInput,
  SeiRawMap,
  SeiRawValue,
  SeiRegistrarAnotacaoParams,
  SeiRegistrarOuvidoriaParams,
  SeiRelacionarProcessoParams,
  SeiRemetente,
  SeiRetirarDocumentoBlocoParams,
  SeiRetirarProcessoBlocoParams,
  SeiRetornoConsultaBloco,
  SeiRetornoConsultaDocumento,
  SeiRetornoConsultaProcedimento,
  SeiRetornoConsultaPublicacao,
  SeiRetornoEnvioEmail,
  SeiRetornoGeracaoProcedimento,
  SeiRetornoInclusaoDocumento,
  SeiScalarSoapValue,
  SeiSecaoDocumento,
  SeiSecaoDocumentoInput,
  SeiSerie,
  SeiSoapArrayValue,
  SeiSoapCallOptions,
  SeiSoapParamValue,
  SeiSoapStructValue,
  SeiSobrestarProcessoParams,
  SeiTipoConferencia,
  SeiTipoPrioridade,
  SeiTipoProcedimento,
  SeiUnidade,
  SeiUnidadeProcedimentoAberto,
  SeiUsuario,
} from "./types"
